### ISSUE TITLE
第四章deskmark编译问题

### ISSUE THREAD

**Issue by Robin-ou** [vikingmute/webpack-react-codes#26]
chapter4/part1/app/components/Deskmark/index.jsx 
  // new item
    if (!item.id) {
      items = [...items, {
        ...item,
        id: uuid.v4(),
        time: new Date().getTime(),
}];

编译追加数组的时候总是提示报错。。。不知道什么原因

**Comment by nighca** [comment]
@Robin-ou 麻烦提供下具体的错误信息哈

**Comment by Robin-ou** [comment]
at D:\WebStormSpace\MyReact\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (D:\WebStormSpace\MyReact\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at D:\WebStormSpace\MyReact\node_modules\webpack\node_modules\enhanced-resolve\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
 @ ./app/app.jsx 5:0-40

ERROR in ./app/components/Deskmark/index.jsx
Module build failed: SyntaxError: D:/WebStormSpace/MyReact/app/components/Deskmark/index.jsx: Unexpected token (45:16)

  43 |         if (item.id) {
  44 |             items = [...items, {
> 45 |                 ...item,
     |                 ^
  46 |                 id: uuid.v4(),
  47 |                 time: new Date().getTime,
  48 |             }];

 @ ./app/app.jsx 15:16-46
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 540 kB
         + 3 hidden modules
webpack: Failed to compile.

**Comment by Robin-ou** [comment]
ERROR in ./~/bootstrap/scss/bootstrap.scss
Module parse failed: D:\WebStormSpace\MyReact\node_modules\bootstrap\scss\bootstrap.scss Unexpected character '@' (9:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (9:0)
    at Parser.pp$4.raise (D:\WebStormSpace\MyReact\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (D:\WebStormSpace\MyReact\node_modules\webpack\node_modules\acorn\dist\acorn.js:2756:10)
    at Parser.pp$7.readToken (D:\WebStormSpace\MyReact\node_modules\webpack\node_modules\acorn\dist\acorn.js:2477:17)
    at Parser.pp$7.nextToken (D:\WebStormSpace\MyReact\node_modules\webpack\node_modules\acorn\dist\acorn.js:2468:15)
    at Parser.parse (D:\WebStormSpace\MyReact\node_modules\webpack\node_modules\acorn\dist\acorn.js:515:10)
    at Object.parse (D:\WebStormSpace\MyReact\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (D:\WebStormSpace\MyReact\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (D:\WebStormSpace\MyReact\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (D:\WebStormSpace\MyReact\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (D:\WebStormSpace\MyReact\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at D:\WebStormSpace\MyReact\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (D:\WebStormSpace\MyReact\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at D:\WebStormSpace\MyReact\node_modules\webpack\node_modules\enhanced-resolve\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
 @ ./app/app.jsx 5:0-40

**Comment by nighca** [comment]
@Robin-ou 第一个问题，跟 https://github.com/vikingmute/webpack-react-codes/issues/16 这里的问题是同一个，可以参考下哈

**Comment by nighca** [comment]
第二个问题，看起来是 webpack 的配置有问题，麻烦检查下 `webpack.config.js` 中的 `loader` 配置里是不是正确配置了：

```javascript
{
  test: /\.scss$/,
  loaders: ['style', 'css', 'sass']
}
```

**Comment by Robin-ou** [comment]
ERROR in ./app/components/Deskmark/index.jsx
Module build failed: SyntaxError: D:/WebStormSpace/MyReact/app/components/Deskmark/index.jsx: Unexpected token (45:16)

  43 |         if (item.id) {
  44 |             items = [...items, {
> 45 |                 ...item,
     |                 ^
  46 |                 id: uuid.v4(),
  47 |                 time: new Date().getTime,
  48 |             }];

 @ ./app/app.jsx 15:16-46

ERROR in Cannot find module 'node-sass'
 @ ./~/bootstrap/scss/bootstrap.scss 4:14-96 13:2-17:4 14:20-102
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 540 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./~/html-webpack-plugin/default_index.ejs 550 bytes {0} [built]
        [1] ./~/html-webpack-plugin/~/lodash/lodash.js 540 kB {0} [built]
        [2] (webpack)/buildin/module.js 251 bytes {0} [built]
webpack: Failed to compile.
第一个CSS的问题解决，这个还是编译不通过

**Comment by Robin-ou** [comment]
ERROR in ./app/components/Deskmark/index.jsx
Module build failed: SyntaxError: D:/WebStormSpace/MyReact/app/components/Deskmark/index.jsx: Unexpected token (45:16)

  43 |         if (item.id) {
  44 |             items = [...items, {
> 45 |                 ...item,
     |                 ^
  46 |                 id: uuid.v4(),
  47 |                 time: new Date().getTime,
  48 |             }];

 @ ./app/app.jsx 15:16-46

ERROR in Cannot find module 'lodash.clonedeep'
 @ ./~/bootstrap/scss/bootstrap.scss 4:14-96 13:2-17:4 14:20-102
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 540 kB
         + 3 hidden modules
webpack: Failed to compile.
 
刚刚那个node-sass配的npm install 找不到对应的模块 我在github上自己下了，然后编译又出现lodash.clonedeep这个模块找不到。。。

**Comment by Robin-ou** [comment]
我试了好几次，npm install node-sass@3.4.2  一直不能安装，原因应该是包的作者删了对应的版本，然后书里面的lodash这个模块又必须这个版本的。。。关于版本适配问题还望大神帮忙看看，菜鸟的一点小见解，不知道对不对

**Comment by nighca** [comment]
@Robin-ou 你好，不好意思这么晚回复。不过你说的情况好像有点问题：

1. node-sass@3.4.2 这个版本是有的，我这也是可以安装的，你 `npm info node-sass` 可以看到所有的版本。如果还是安装不了，一方面可能是你的 npm registry 配置问题，可以确认下是不是官方源或淘宝源；另外一方面的原因也可能是 #15 这里的原因，可以参考下

2. 这里不是 `lodash` 依赖 `node-sass`，应该是后者依赖前者。这里的错误是在处理一个 `scss` 文件的时候报的，所以是 `node-sass` 的代码执行时没找到它的依赖导致的，原因应该也就是通过手动下载而不是 npm 安装

所以这里能通过 npm 正确安装上 `node-sass` 的话就不会有问题了

**Comment by Robin-ou** [comment]
额，谢谢！我仔细研究了错误提示，貌似确实需要Python环境，而且还是2.7.x的。。。，不过我装Python后还是有问题，最后通过切换到cnpm解决了。。。

**Comment by nighca** [comment]
👌
