### ISSUE TITLE
一点建议和问题

### ISSUE THREAD

**Issue by RockyAo** [vikingmute/webpack-react-codes#7]
## 建议
第三章67页创建的 webpack.config.js文件中
~~~
entry:path.resolve(APP_PATH,"index.jsx")
~~~
这个地方指定文件名为index.jsx 69页创建的文件名为app.jsx。这里会导致npm报文件找不到。。初学有点费解。

~~~
var APP_PATH = path.resolve(ROOT_PATH,'app');
~~~

这个地方根目录下创建了app文件夹，应该提醒读者。新手所以没创建这个目录  ，同样报了文件找不到

## 问题

npm run dev 时报错

~~~
ERROR in ./app/app.jsx
Module build failed: Error: /Users/RockyAo/Desktop/code/webLearn/React/node_modules/eslint-config-airbnb/rules/react-a11y.js:
       	Configuration for rule "jsx-a11y/anchor-has-content" is invalid:
       	Value "" is the wrong type.

Referenced from: airbnb
Referenced from: /Users/RockyAo/Desktop/code/webLearn/React/.eslintrc
    at validateRuleOptions (/Users/RockyAo/Desktop/code/webLearn/React/node_modules/eslint/lib/config/config-validator.js:115:15)
    at Object.keys.forEach.id (/Users/RockyAo/Desktop/code/webLearn/React/node_modules/eslint/lib/config/config-validator.js:162:13)
    at Array.forEach (native)
    at Object.validate (/Users/RockyAo/Desktop/code/webLearn/React/node_modules/eslint/lib/config/config-validator.js:161:35)
    at load (/Users/RockyAo/Desktop/code/webLearn/React/node_modules/eslint/lib/config/config-file.js:522:19)
    at configExtends.reduceRight.e (/Users/RockyAo/Desktop/code/webLearn/React/node_modules/eslint/lib/config/config-file.js:391:36)
    at Array.reduceRight (native)
    at applyExtends (/Users/RockyAo/Desktop/code/webLearn/React/node_modules/eslint/lib/config/config-file.js:362:28)
    at load (/Users/RockyAo/Desktop/code/webLearn/React/node_modules/eslint/lib/config/config-file.js:529:22)
    at configExtends.reduceRight.e (/Users/RockyAo/Desktop/code/webLearn/React/node_modules/eslint/lib/config/config-file.js:391:36)
    at Array.reduceRight (native)
    at applyExtends (/Users/RockyAo/Desktop/code/webLearn/React/node_modules/eslint/lib/config/config-file.js:362:28)
    at Object.load (/Users/RockyAo/Desktop/code/webLearn/React/node_modules/eslint/lib/config/config-file.js:529:22)
    at loadConfig (/Users/RockyAo/Desktop/code/webLearn/React/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/Users/RockyAo/Desktop/code/webLearn/React/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/Users/RockyAo/Desktop/code/webLearn/React/node_modules/eslint/lib/config.js:256:22)
 @ multi app
~~~

这个错应该是eslint抛出来的，不知道为啥。eslint的配置文件我写的和书上一样的。去掉webpack 配置文件中的
~~~
// preLoaders:[
      //     {
      //        test:/\.jsx?$/,
      //        loaders:['eslint'],
      //        include:APP_PATH
      //     }
      // ],
~~~
网页可以正常工作

**Comment by vikingmute** [comment]
@RockyAo 谢谢你的提议 我会写到勘误表里面

至于你的错误 原因在这里 https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/116  原因就是eslint－aribnb－config 只支持 eslint-plugin-jsx-a11y v2 版本， 不支持v3 版本，所以建议你用这个repo里面的代码，里面用了npm shrinkwrap来确保版本的正确。

**Comment by RockyAo** [comment]
@vikingmute 好的，我去研究下。非常感谢
